### ISSUE TITLE
Testing using mocha

### ISSUE THREAD

**Issue by yannh** [fastly/compute-starter-kit-javascript-default#23]
Hello, how would unit testing of the handleRequest function be done, using for example Mocha? Could you add a simple example? That would be very useful, thanks!

**Comment by JakeChampion** [comment]
I've not seen a project using mocha for unit-testing JavaScript Compute applications - there is this [Fastly Compute Jest Preset](https://github.com/ysugimoto/jest-preset-fastly-js-compute) which enables unit-testing which could be a helpful place to start
