### ISSUE TITLE
Deploy Error: unable to parse API response: missing field `id` at line 1 column 59

### ISSUE THREAD

**Issue by grokify** [fastly/compute-starter-kit-javascript-default#24]
After clicking the "Deploy" button in step "4. Deploy Application", I receive the following error HTTP Status 500 error from https://deploy.edgecompute.app/deploy

I'm launching the flow by clicking the "Deploy to Fastly" button on this page:

https://github.com/fastly/compute-starter-kit-javascript-default

at the latest commit: 3632e1e78d18b592ec8fe256305b7903398a9c34

Here's the message.

> We were unable to process your request
> 
> unable to parse API response: missing field `id` at line 1 column 59
> 
> You may be able to go back and try again, otherwise use one of the options below to reset your progress:
> 
> [ Cancel deployment ] [ Log out ]

<img width="879" alt="DeployToFastlyErrorAPIResponseMissingFieldID" src="https://user-images.githubusercontent.com/209872/169849798-5a17b786-ba83-4f51-9471-aa8506d4214c.png">

**Comment by mufudzimasaire** [comment]
Hi there, facing a similar issue here as well. 

![Screenshot 2022-10-20 at 12 17 07](https://user-images.githubusercontent.com/4486874/196934640-c084989e-d142-4e42-9381-48bcbdf4e272.png)

**Comment by kailan** [comment]
Hi @grokify and @mufudzimasaire, thanks for reporting this.

We have made some changes to the way errors are handled in the application since your initial reports. Would you be able to try again and provide the latest error message? Thanks in advance.

**Comment by JakeChampion** [comment]
I've tried the deploy button in Safari, Chrome, and Firefox - It looks to be working in all three for me.
@grokify and/or @mufudzimasaire, do you know what browser you came across this issue with?

**Comment by triblondon** [comment]
No longer reproable, let's assume fixed.  Please reopen if you encounter this again.
